-- Fuente: http://www.countryareacode.net

INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AF','AFG','Afganistán','+93');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AL','ALB','Albania','+355');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DE','DEU','Alemania','+49');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AD','AND','Andorra','+376');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AO','AGO','Angola','+244');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AI','AIA','Anguila','+1 264');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AQ','ATA','Antártida','+672');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SA','SAU','Arabia Saudita','+966');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DZ','DZA','Argelia','+213');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AR','ARG','Argentina','+54');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AM','ARM','Armenia','+374');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AW','ABW','Aruba','+297');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AU','AUS','Australia','+61');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AT','AUT','Austria','+43');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AZ','AZE','Azerbaiyán','+994');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BS','BHS','Bahamas','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BH','BHR','Bahréin','+973');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BD','BGD','Bangladesh','+880');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BB','BRB','Barbados','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BE','BEL','Bélgica','+32');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BZ','BLZ','Belice','+501');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BJ','BEN','Benín','+229');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BM','BMU','Bermudas','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BY','BLR','Bielorrusia','+375');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MM','MMR','Birmania (Myanmar)','+95');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BO','BOL','Bolivia','+591');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BA','BIH','Bosnia y Herzegovina','+387');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BW','BWA','Botsuana','+267');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BR','BRA','Brasil','+55');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BN','BRN','Brunéi','+673');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BG','BGR','Bulgaria','+359');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BF','BFA','Burkina Faso','+226');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BI','BDI','Burundi','+257');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BT','BTN','Bután','+975');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CV','CPV','Cabo Verde','+238');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KH','KHM','Camboya','+855');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CM','CMR','Camerún','+237');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CA','CAN','Canadá','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CL','CHL','Chile','+56');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CN','CHN','China','+86');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CY','CYP','Chipre','+357');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CO','COL','Colombia','+57');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KM','COM','Comoras','+269');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KP','PRK','Corea del Norte','+850');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KR','KOR','Corea del Sur','+82');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CI','CIV','Costa de Marfil','+225');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CR','CRI','Costa Rica','+506');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('HR','HRV','Croacia','+385');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CU','CUB','Cuba','+53');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CW','CUW','Curazao','+599');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DK','DNK','Dinamarca','+45');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DJ','DJI','Djibuti','+253');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DM','DMA','Dominica','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('EC','ECU','Ecuador','+593');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('EG','EGY','Egipto','+20');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('EH','ESH','El Sáhara Español','+212');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SV','SLV','El Salvador','+503');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VA','VAT','El Vaticano','+39');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AE','ARE','Emiratos Árabes Unidos','+971');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ER','ERI','Eritrea','+291');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SK','SVK','Eslovaquia','+421');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SI','SVN','Eslovenia','+386');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ES','ESP','España','+34');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('US','USA','Estados Unidos','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('EE','EST','Estonia','+372');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ET','ETH','Etiopía','+251');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PH','PHL','Filipinas','+63');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FI','FIN','Finlandia','+358');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FJ','FJI','Fiyi','+679');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FR','FRA','Francia','+33');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GA','GAB','Gabón','+241');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GM','GMB','Gambia','+220');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GE','GEO','Georgia','+995');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GH','GHA','Ghana','+233');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GI','GIB','Gibraltar','+350');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GR','GRC','Grecia','+30');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GL','GRL','Groenlandia','+299');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GP','GLP','Guadalupe','+590');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GU','GUM','Guam','+1 671');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GT','GTM','Guatemala','+502');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GN','GIN','Guinea','+224');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GQ','GNQ','Guinea Ecuatorial','+240');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GW','GNB','Guinea-Bissáu','+245');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GY','GUY','Guyana','+592');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('HT','HTI','Haití','+509');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NL','NLD','Holanda','+31');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('HN','HND','Honduras','+504');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('HK','HKG','Hong Kong','+852');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('HU','HUN','Hungría','+36');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IN','IND','India','+91');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ID','IDN','Indonesia','+62');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IQ','IRQ','Irak','+964');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IR','IRN','Irán','+98');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IE','IRL','Irlanda','+353');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IM','IMN','Isla de Man','+44');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NF','NFK','Isla Norfolk','+672');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IS','ISL','Islandia','+354');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KY','CYM','Islas Caimán','+1-345');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CK','COK','Islas Cook','+682');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FO','FRO','Islas Feroe','+298');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FK','FLK','Islas Malvinas','+500');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MP','MNP','Islas Marianas del Norte','+1 670');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MH','MHL','Islas Marshall','+692');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PN','PCN','Islas Pitcairn','+870');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SB','SLB','Islas Salomón','+677');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VG','VGB','Islas Vírgenes Británicas','+1 284');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IL','ISR','Israel','+972');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('IT','ITA','Italia','+39');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('JM','JAM','Jamaica','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('JP','JPN','Japón','+81');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('JO','JOR','Jordania','+962');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KZ','KAZ','Kazajistán','+7');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KE','KEN','Kenia','+254');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KG','KGZ','Kirgizistán','+996');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KI','KIR','Kiribati','+686');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('XK','XKX','Kosovo','+381');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KW','KWT','Kuwait','+965');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LA','LAO','Laos','+856');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LS','LSO','Lesoto','+266');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LV','LVA','Letonia','+371');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LB','LBN','Líbano','+961');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LR','LBR','Liberia','+231');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LY','LBY','Libia','+218');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LI','LIE','Liechtenstein','+423');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LT','LTU','Lituania','+370');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LU','LUX','Luxemburgo','+352');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MO','MAC','Macao','+853');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MK','MKD','Macedonia','+389');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MG','MDG','Madagascar','+261');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MY','MYS','Malasia','+60');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MW','MWI','Malaui','+265');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MV','MDV','Maldivas','+960');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ML','MLI','Mali','+223');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MT','MLT','Malta','+356');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MA','MAR','Marruecos','+212');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MU','MUS','Mauricio','+230');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MR','MRT','Mauritania','+222');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MX','MEX','México','+52');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('FM','FSM','Micronesia','+691');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MD','MDA','Moldavia','+373');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MC','MCO','Mónaco','+377');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MN','MNG','Mongolia','+976');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ME','MNE','Montenegro','+382');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MS','MSR','Montserrat','+1 664');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MZ','MOZ','Mozambique','+258');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NA','NAM','Namibia','+264');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NR','NRU','Nauru','+674');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NP','NPL','Nepal','+977');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NI','NIC','Nicaragua','+505');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NE','NER','Níger','+227');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NG','NGA','Nigeria','+234');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NU','NIU','Niue','+683');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NO','NOR','Noruega','+47');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NC','NCL','Nueva Caledonia','+687');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('NZ','NZL','Nueva Zelanda','+64');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('OM','OMN','Omán','+968');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PK','PAK','Pakistán','+92');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PW','PLW','Palau','+680');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PA','PAN','Panamá','+507');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PG','PNG','Papúa Nueva Guinea','+675');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PY','PRY','Paraguay','+595');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PE','PER','Perú','+51');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PF','PYF','Polinesia Francesa','+689');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PL','POL','Polonia','+48');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PT','PRT','Portugal','+351');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PR','PRI','Puerto Rico','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('QA','QAT','Qatar','+974');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('GB','GBR','Reino Unido','+44');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CF','CAF','República Centroafricana','+236');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CZ','CZE','República Checa','+420');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SS','SSD','República de Sudán del Sur','+211');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CG','COG','República del Congo','+242');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CD','COD','República Democrática del Congo','+243');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('DO','DOM','República Dominicana','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('RE','REU','Reunión','+262');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('RW','RWA','Ruanda','+250');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('RO','ROU','Rumanía','+40');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('RU','RUS','Rusia','+7');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('WS','WSM','Samoa','+685');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('AS','ASM','Samoa Americana','+1 684');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('BL','BLM','San Bartolomé','+590');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('KN','KNA','San Cristóbal y Nevis','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SM','SMR','San Marino','+378');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('MF','MAF','San Martín','+1 599');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('PM','SPM','San Pedro y Miquelón','+508');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VC','VCT','San Vicente y las Granadinas','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SH','SHN','Santa Elena','+290');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LC','LCA','Santa Lucía','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ST','STP','Santo Tomé y Príncipe','+239');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SN','SEN','Senegal','+221');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('RS','SRB','Serbia','+381');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SC','SYC','Seychelles','+248');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SL','SLE','Sierra Leona','+232');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SG','SGP','Singapur','+65');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SY','SYR','Siria','+963');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SO','SOM','Somalia','+252');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('LK','LKA','Sri Lanka','+94');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ZA','ZAF','Sudáfrica','+27');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SD','SDN','Sudán','+249');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SE','SWE','Suecia','+46');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('CH','CHE','Suiza','+41');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SR','SUR','Surinam','+597');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('SZ','SWZ','Swazilandia','+268');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TH','THA','Tailandia','+66');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TW','TWN','Taiwán','+886');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TZ','TZA','Tanzania','+255');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TJ','TJK','Tayikistán','+992');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TL','TLS','Timor Oriental','+670');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TG','TGO','Togo','+228');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TK','TKL','Tokelau','+690');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TT','TTO','Trinidad y Tobago','+1');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TN','TUN','Túnez','+216');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TM','TKM','Turkmenistán','+993');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TR','TUR','Turquía','+90');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('TV','TUV','Tuvalu','+688');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('UA','UKR','Ucrania','+380');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('UG','UGA','Uganda','+256');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('UY','URY','Uruguay','+598');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('UZ','UZB','Uzbekistán','+998');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VU','VUT','Vanuatu','+678');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VE','VEN','Venezuela','+58');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('VN','VNM','Vietnam','+84');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('YE','YEM','Yemen','+967');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ZM','ZMB','Zambia','+260');
INSERT INTO pais(codigoISO2,codigoISO3,pais,prefijoTelef) VALUES ('ZW','ZWE','Zimbabue','+263');

-- Miguel Ángel Damián